version: '2'
services:
    telebot:
        build:
            context: ./
        volumes:
            - ./app:/go/src/github.com/user/myProject/app
        ports:
            - 80:3000
        container_name: telebot
        command: gin -i run main.go

